apiVersion: apps/v1
kind: Deployment
metadata:
  name: storybook-dep-qa
  labels:
    app: storybook-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storybook-app-qa
  template:
    metadata:
      labels:
        app: storybook-app-qa
    spec:
      containers:
        - name: storybook-qa
          image: REPO_IMAGE
          ports:
            - name: storybook-qa
              containerPort: 6008
